import { User } from "../generated";

export const players: User[] = [
  {
    id: `uuid-1`,
    created: new Date(),
    updated: new Date(),
    lastLogin: new Date(),
    version: 1,
    name: `Drunkenskarl`,
    gamerTag: `Drunkenskarl`,
    email: `milo@sideqst.com`,
    suspended: false,
    verified: true,
    profile: {
      id: `uuid-profile-1`,
      bio: `Fortune baby...`,
      tags: [`Admin`, `Sideqst`, `Owner`],
      lolName: `Drunkenskarl`,
      avatarUrl: `https://ddragon.leagueoflegends.com/cdn/11.9.1/img/profileicon/4895.png`,
      level: 100,
      points: 10000,
      wins: 1000,
      entered: 1234,
      hosted: 200,
      status: `online`,
    },
  },
  {
    id: `uuid-2`,
    created: new Date(),
    updated: new Date(),
    lastLogin: new Date(),
    version: 1,
    name: `k3soju`,
    gamerTag: `k3soju`,
    email: `k3soju@cloud9.gg`,
    suspended: false,
    verified: true,
    profile: {
      id: `uuid-profile-2`,
      bio: `First of Eifph...`,
      tags: [`Streamer`, `Challenger`],
      lolName: `k3soju`,
      avatarUrl: `https://ddragon.leagueoflegends.com/cdn/11.9.1/img/profileicon/4832.png`,
      level: 25,
      points: 2542,
      wins: 54,
      entered: 89,
      hosted: 2,
      status: `busy`,
    },
  },
];
